export const FETCH_RESIDENT = "FETCH_RESIDENT";
export const FETCH_RESIDENT_SUCCESS = "FETCH_RESIDENT_SUCCESS";

export const ADD_RESIDENT = "ADD_RESIDENT";
export const ADD_RESIDENT_SUCCESS = "ADD_RESIDENT_SUCCESS";

export const REMOVE_RESIDENT_FROM_FLAT = "REMOVE_RESIDENT_FROM_FLAT";
export const REMOVE_RESIDENT_FROM_FLAT_SUCCESS =
  "REMOVE_RESIDENT_FROM_FLAT_SUCCESS";
