export const FETCH_FLAT = "FETCH_FLAT";
export const FETCH_FLAT_SUCCESS = "FETCH_FLAT_SUCCESS";

export const FETCH_FLAT_BY_SORT = "FETCH_FLAT_BY_SORT";
export const FETCH_FLAT_BY_SORT_SUCCESS = "FETCH_FLAT_BY_SORT_SUCCESS";

export const CREATE_FLAT = "CREATE_FLAT";
export const CREATE_FLAT_SUCCESS = "CREATE_FLAT_SUCCESS";
